Pilot 2009
PilotDataPlatform/workspace pull request #7
Opened 2022-12-01 19:38 UTC by gregmccoy

## Summary
Adding bulk add  users to guacamole endpoint

## JIRA Issues

PILOT-2009

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-12-02 14:46 UTC, erikdvlp requested changes

2022-12-02 14:46 UTC, erikdvlp commented on app/routers/api_guacamole/api_permission.py
> +    logger = LoggerFactory('api_permisison').get_logger()
> `api_permisison`

Find & replace please.

Also, we don't use the new configurable logger in this repo?

2022-12-05 15:39 UTC, gregmccoy commented on app/routers/api_guacamole/api_permission.py
> +    logger = LoggerFactory('api_permisison').get_logger()
Fixed the typo and updated to the new logger format

2022-12-05 18:46 UTC, erikdvlp approved these changes

2022-12-05 19:37 UTC, merged